name: 'Publish aux4 Package'
description: 'Build and publish an aux4 package to hub.aux4.io with GitHub release'
author: 'aux4'

branding:
  icon: 'package'
  color: 'gray-dark'

inputs:
  level:
    description: 'Release level (patch, minor, major)'
    required: false
    default: 'patch'
  aux4_token:
    description: 'aux4 access token for publishing to hub.aux4.io'
    required: true
  github_token:
    description: 'GitHub token for creating releases'
    required: true
  working_directory:
    description: 'Working directory containing the repository'
    required: false
    default: '.'
  package_directory:
    description: 'Directory containing the package .aux4 file'
    required: false
    default: 'package'
  aux4_image:
    description: 'Docker image for aux4'
    required: false
    default: 'aux4/aux4:latest'

outputs:
  version:
    description: 'The new package version'
    value: ${{ steps.version.outputs.version }}
  scope:
    description: 'The package scope'
    value: ${{ steps.version.outputs.scope }}
  name:
    description: 'The package name'
    value: ${{ steps.version.outputs.name }}

runs:
  using: 'composite'
  steps:
    - name: Configure git
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Pull latest changes
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        git pull --rebase origin ${{ github.ref_name }}

    - name: Get current package info
      id: current
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        PACKAGE_AUX4="${{ inputs.package_directory }}/.aux4"
        if [ ! -f "$PACKAGE_AUX4" ]; then
          echo "::error::Package metadata not found at ${PACKAGE_AUX4}"
          exit 1
        fi
        SCOPE=$(jq -r '.scope' "$PACKAGE_AUX4")
        NAME=$(jq -r '.name' "$PACKAGE_AUX4")
        CURRENT_VERSION=$(jq -r '.version' "$PACKAGE_AUX4")
        echo "scope=${SCOPE}" >> $GITHUB_OUTPUT
        echo "name=${NAME}" >> $GITHUB_OUTPUT
        echo "current_version=${CURRENT_VERSION}" >> $GITHUB_OUTPUT
        echo "::notice::Found package ${SCOPE}/${NAME} at version ${CURRENT_VERSION}"

    - name: Increment version
      id: version
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        PACKAGE_AUX4="${{ inputs.package_directory }}/.aux4"
        CURRENT_VERSION="${{ steps.current.outputs.current_version }}"
        LEVEL="${{ inputs.level }}"

        IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"

        case "$LEVEL" in
          major)
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
            ;;
          minor)
            MINOR=$((MINOR + 1))
            PATCH=0
            ;;
          patch)
            PATCH=$((PATCH + 1))
            ;;
        esac

        NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
        echo "version=${NEW_VERSION}" >> $GITHUB_OUTPUT
        echo "scope=${{ steps.current.outputs.scope }}" >> $GITHUB_OUTPUT
        echo "name=${{ steps.current.outputs.name }}" >> $GITHUB_OUTPUT

        # Update package/.aux4 file
        jq --arg v "$NEW_VERSION" '.version = $v' "$PACKAGE_AUX4" > "${PACKAGE_AUX4}.tmp" && mv "${PACKAGE_AUX4}.tmp" "$PACKAGE_AUX4"

        echo "::notice::Version bumped from ${CURRENT_VERSION} to ${NEW_VERSION}"

    - name: Pull latest aux4 image
      shell: bash
      run: |
        docker pull ${{ inputs.aux4_image }}

    - name: Build package
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        echo "::group::Package directory contents"
        ls -la ${{ inputs.package_directory }}/
        echo "::endgroup::"

        docker run --rm \
          --user $(id -u):$(id -g) \
          -v $(pwd):/workspace \
          -w /workspace \
          ${{ inputs.aux4_image }} \
          aux4 pkger build ${{ inputs.package_directory }}

        echo "::group::Generated package contents"
        SCOPE=$(jq -r '.scope' "${{ inputs.package_directory }}/.aux4")
        NAME=$(jq -r '.name' "${{ inputs.package_directory }}/.aux4")
        VERSION=$(jq -r '.version' "${{ inputs.package_directory }}/.aux4")
        unzip -l "${SCOPE}_${NAME}_${VERSION}.zip" || echo "Could not list zip contents"
        echo "::endgroup::"

    - name: Publish to hub.aux4.io
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        AUX4_ACCESS_TOKEN: ${{ inputs.aux4_token }}
      run: |
        SCOPE="${{ steps.current.outputs.scope }}"
        NAME="${{ steps.current.outputs.name }}"
        VERSION="${{ steps.version.outputs.version }}"
        PACKAGE_FILE="${SCOPE}_${NAME}_${VERSION}.zip"

        # Trim any whitespace/newlines from token
        AUX4_ACCESS_TOKEN=$(echo -n "$AUX4_ACCESS_TOKEN" | tr -d '[:space:]')

        docker run --rm \
          --user $(id -u):$(id -g) \
          -v $(pwd):/workspace \
          -w /workspace \
          -e AUX4_ACCESS_TOKEN="${AUX4_ACCESS_TOKEN}" \
          --entrypoint sh \
          ${{ inputs.aux4_image }} \
          -c 'aux4 aux4 pkger publish "'"${PACKAGE_FILE}"'"'

    - name: Commit and tag
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        VERSION="${{ steps.version.outputs.version }}"
        PACKAGE_AUX4="${{ inputs.package_directory }}/.aux4"

        git add "$PACKAGE_AUX4"
        git commit -m "release: ${VERSION}"
        git tag -a "v${VERSION}" -m "release: v${VERSION}"

    - name: Push changes and tags
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        git push origin ${{ github.ref_name }}
        git push origin --tags

    - name: Create GitHub Release
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        SCOPE="${{ steps.current.outputs.scope }}"
        NAME="${{ steps.current.outputs.name }}"
        VERSION="${{ steps.version.outputs.version }}"
        PACKAGE_FILE="${SCOPE}_${NAME}_${VERSION}.zip"

        if [ -f "${PACKAGE_FILE}" ]; then
          gh release create "v${VERSION}" \
            "${PACKAGE_FILE}" \
            --title "Release v${VERSION}" \
            --notes "Release of ${SCOPE}/${NAME} v${VERSION}"
        else
          gh release create "v${VERSION}" \
            --title "Release v${VERSION}" \
            --notes "Release of ${SCOPE}/${NAME} v${VERSION}"
        fi

    - name: Cleanup
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        SCOPE="${{ steps.current.outputs.scope }}"
        NAME="${{ steps.current.outputs.name }}"
        VERSION="${{ steps.version.outputs.version }}"
        rm -f "${SCOPE}_${NAME}_${VERSION}.zip"
